services:
  - type: web
    name: nactivi-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: BOT_TOKEN
        value: 8668060570:AAEeED_4VOiyX82dhmaq0CjeE6A-iSHC4hc
      - key: WEBHOOK_URL
        value: https://nactivi-bot.onrender.com   # ← غيّر هذا بعد الرفع
      - key: ADMIN_SECRET
        value: nactivi_admin_2025                  # ← غيّر هذا لكلمة سر قوية
      - key: PYTHON_VERSION
        value: "3.11.0"
    disk:
      name: db
      mountPath: /opt/render/project/src
      sizeGB: 1
